Emptyset = set()
number1 = int(input("Enter 1st number: "))
Emptyset.add(number1)
number2 = int(input("Enter 2nd number: "))
Emptyset.add(number2)
number3 = int(input("Enter 3rd number: "))
Emptyset.add(number3)
number4 = int(input("Enter 4th number: "))
Emptyset.add(number4)
number5 = int(input("Enter 5th number: "))
Emptyset.add(number5)
number6 = int(input("Enter 6th number: "))
Emptyset.add(number6)   
number7 = int(input("Enter 7th number: "))
Emptyset.add(number7)
number8 = int(input("Enter 8th number: "))
Emptyset.add(number8)

print(Emptyset)
